DROP TABLE IF EXISTS site_access;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS role, DROP COLUMN IF EXISTS display_name;
