import { ExternalLink, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PublicHeader } from '../components/PublicHeader'
import { useI18n } from '../i18n/I18nProvider'

export function ContactPage({ authenticated = false, accountName, onLogout }: { authenticated?: boolean; accountName?: string; onLogout?: () => void }) {
  const { language } = useI18n()
  const text = (th: string, en: string) => language === 'th' ? th : en
  const investmentLink = authenticated ? '/sites/new' : '/login?mode=register'
  return <main className="landing-page public-site"><PublicHeader authenticated={authenticated} accountName={accountName} onLogout={onLogout}/><section className="public-contact"><div className="public-contact-intro"><h2>{text('ปรึกษาเรื่องทำเล EV Station', 'Consult about your EV Station site')}</h2><p>{text('เริ่มจากส่งทำเลของคุณเข้าระบบ ทีม RBC จะใช้ข้อมูลเพื่อประเมินเบื้องต้นและติดต่อกลับตามข้อมูลบัญชีที่คุณให้ไว้', 'Start by submitting your site. The RBC team uses those details for an initial review and follows up through your account details.')}</p><Link className="landing-cta" to={investmentLink}>{text('ส่งทำเลเพื่อปรึกษา', 'Submit a site to consult')}<MessageCircle size={19}/></Link></div><address className="public-company-contact"><strong>{text('ข้อมูลติดต่อบริษัท', 'Company contact')}</strong><span className="public-company-name">{text('บริษัท รุ่งอรุณบรอดคาสติ้ง จำกัด', 'Rung Arun Broadcasting Co., Ltd.')}</span><a href="tel:+6629707552"><Phone size={18}/>02-970-7552</a><a href="mailto:rbcevstation@gmail.com"><Mail size={18}/>rbcevstation@gmail.com</a><span className="public-company-address"><MapPin size={18}/>{text('เลขที่ 9 ซ.รามอินทรา 21 แยก 1 ถนนรามอินทรา แขวงท่าแร้ง เขตบางเขน กรุงเทพมหานคร 10220', '9 Soi Ramintra 21 Yaek 1, Ramintra Road, Tha Raeng, Bang Khen, Bangkok 10220')}</span><div className="public-company-map"><iframe title={text('แผนที่บริษัท รุ่งอรุณบรอดคาสติ้ง จำกัด', 'Rung Arun Broadcasting company location')} src="https://www.google.com/maps?q=13.8715549,100.6212071&z=16&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a href="https://maps.app.goo.gl/xp8cgS2UeEvjpai69" target="_blank" rel="noreferrer">{text('เปิดใน Google Maps', 'Open in Google Maps')}<ExternalLink size={16}/></a></div><div className="public-contact-channels"><a className="public-contact-channel line" href="https://line.me/R/ti/p/@424cdtee" target="_blank" rel="noreferrer"><span className="public-channel-mark">LINE</span><span><strong>{text('เพิ่มเพื่อนใน LINE', 'Add us on LINE')}</strong><small>@424cdtee</small></span><ExternalLink size={16}/></a><a className="public-contact-channel facebook" href="https://www.facebook.com/profile.php?id=100083313259502" target="_blank" rel="noreferrer"><span className="public-channel-mark">f</span><span><strong>{text('ติดตาม Facebook', 'Follow on Facebook')}</strong><small>RBC Ev Station</small></span><ExternalLink size={16}/></a></div></address></section></main>
}
