import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ShieldCheck, UserPlus, Users } from 'lucide-react'
import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { useI18n } from '../i18n/I18nProvider'
import { api } from '../services/api'
import type { UserRole } from '../types/domain'

const roleKeys: Record<UserRole, string> = { owner: 'Owner', sales: 'Sales', viewer: 'Customer' }

export function SettingsPage({ role }: { role: UserRole }) {
	const { t } = useI18n()
	const queryClient = useQueryClient()
	const [selectedSiteID, setSelectedSiteID] = useState('')
	const [newUser, setNewUser] = useState({ displayName: '', email: '', password: '', role: 'sales' as UserRole })
	const [newAccess, setNewAccess] = useState({ userId: '', role: 'sales' as UserRole })
	const users = useQuery({ queryKey: ['users'], queryFn: api.listUsers, enabled: role === 'owner' })
	const sites = useQuery({ queryKey: ['sites'], queryFn: api.listSites, enabled: role === 'owner' })
	const activeSiteID = selectedSiteID || sites.data?.[0]?.id || ''
	const access = useQuery({ queryKey: ['site-access', activeSiteID], queryFn: () => api.listSiteAccess(activeSiteID), enabled: role === 'owner' && Boolean(activeSiteID) })
	const createUser = useMutation({ mutationFn: () => api.createUser(newUser.email, newUser.displayName, newUser.password, newUser.role), onSuccess: () => { setNewUser({ displayName: '', email: '', password: '', role: 'sales' }); queryClient.invalidateQueries({ queryKey: ['users'] }) } })
	const setAccess = useMutation({ mutationFn: () => api.setSiteAccess(activeSiteID, newAccess.userId, newAccess.role), onSuccess: () => { setNewAccess({ userId: '', role: 'sales' }); queryClient.invalidateQueries({ queryKey: ['site-access', activeSiteID] }) } })
	const removeAccess = useMutation({ mutationFn: (userID: string) => api.deleteSiteAccess(activeSiteID, userID), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['site-access', activeSiteID] }) })

	if (role !== 'owner') return <Navigate to="/" replace />
	if (users.isLoading || sites.isLoading) return <LoadingState label={t('Loading page…')} />
	if (users.isError || sites.isError) return <ErrorState error={users.error || sites.error} />
	const userName = (id: string) => users.data?.find(user => user.id === id)?.displayName || id
	return <div><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-brand"><ShieldCheck size={23}/></span><div><h1 className="page-title">{t('Access management')}</h1><p className="mt-1 text-sm text-muted">{t('Create team accounts and assign access for each customer site.')}</p></div></div>
		<div className="mt-7 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-line bg-white p-6 shadow-panel"><div className="flex items-center gap-2"><UserPlus size={19} className="text-brand"/><h2 className="section-title">{t('Create team account')}</h2></div><form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); createUser.mutate() }}><Field label={t('Display name')}><input required value={newUser.displayName} onChange={event => setNewUser({ ...newUser, displayName: event.target.value })} className="input"/></Field><Field label={t('Email')}><input required type="email" value={newUser.email} onChange={event => setNewUser({ ...newUser, email: event.target.value })} className="input"/></Field><Field label={t('Password')}><input required minLength={8} type="password" value={newUser.password} onChange={event => setNewUser({ ...newUser, password: event.target.value })} className="input"/></Field><Field label={t('Role')}><select value={newUser.role} onChange={event => setNewUser({ ...newUser, role: event.target.value as UserRole })} className="input"><option value="sales">{t('Sales')}</option><option value="viewer">{t('Customer')}</option></select></Field>{createUser.isError && <p className="text-sm text-red-700">{t('Unable to create this user.')}</p>}<button className="button-primary" disabled={createUser.isPending}>{t(createUser.isPending ? 'Creating…' : 'Create user')}</button></form></section>
			<section className="rounded-2xl border border-line bg-white p-6 shadow-panel"><div className="flex items-center gap-2"><Users size={19} className="text-brand"/><h2 className="section-title">{t('Team accounts')}</h2></div><div className="mt-5 space-y-3">{users.data?.map(user => <div key={user.id} className="rounded-xl border border-line px-4 py-3"><p className="font-bold text-ink">{user.displayName}</p><p className="mt-0.5 text-sm text-muted">{user.email} · {t(roleKeys[user.role])}</p></div>)}</div></section></div>
		<section className="mt-6 rounded-2xl border border-line bg-white p-6 shadow-panel"><h2 className="section-title">{t('Assign site access')}</h2><p className="mt-1 text-sm text-muted">{t('Sales can edit assigned sites. Customers can only view assigned sites.')}</p><div className="mt-5 grid gap-4 lg:grid-cols-[1fr_1fr_1fr_auto]"><select value={activeSiteID} onChange={event => setSelectedSiteID(event.target.value)} className="input">{sites.data?.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select><select value={newAccess.userId} onChange={event => setNewAccess({ ...newAccess, userId: event.target.value })} className="input"><option value="">{t('Select user')}</option>{users.data?.filter(user => user.role !== 'owner').map(user => <option key={user.id} value={user.id}>{user.displayName} · {t(roleKeys[user.role])}</option>)}</select><select value={newAccess.role} onChange={event => setNewAccess({ ...newAccess, role: event.target.value as UserRole })} className="input"><option value="sales">{t('Sales')}</option><option value="viewer">{t('Customer')}</option></select><button type="button" className="button-primary justify-center" disabled={!activeSiteID || !newAccess.userId || setAccess.isPending} onClick={() => setAccess.mutate()}>{t(setAccess.isPending ? 'Saving…' : 'Assign')}</button></div>{access.isError || setAccess.isError || removeAccess.isError ? <p className="mt-4 text-sm text-red-700">{t('Unable to update site access. Please try again.')}</p> : null}<div className="mt-6 overflow-hidden rounded-xl border border-line"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-line bg-slate-50 px-4 py-3 text-xs font-bold uppercase tracking-wide text-muted"><span>{t('User')}</span><span>{t('Role')}</span><span>{t('Action')}</span></div>{access.isLoading ? <p className="px-4 py-5 text-sm text-muted">{t('Loading page…')}</p> : access.data?.length ? access.data.map(grant => <div key={grant.userId} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 border-b border-line px-4 py-3 last:border-0"><span className="text-sm font-semibold text-ink">{userName(grant.userId)}</span><span className="text-sm text-muted">{t(roleKeys[grant.role])}</span><button type="button" className="text-sm font-bold text-red-600 hover:underline" disabled={removeAccess.isPending} onClick={() => removeAccess.mutate(grant.userId)}>{t('Remove')}</button></div>) : <p className="px-4 py-5 text-sm text-muted">{t('No users have been assigned to this site yet.')}</p>}</div></section>
	</div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-ink">{label}<span className="mt-1.5 block">{children}</span></label> }
